---
  - name: "Deploying on the kubernetes cluster"
    hosts: localhost
    connection: local 
    
    tasks:
    - name: Deleting older application deployment
      ansible.builtin.shell: |
        kubectl delete -f kubeDeploy/mysql-deployment.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/backend-deployment.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/frontend-deployment.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/mysql-root-credentials.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/mysql-credentials.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/mysql-configmap.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/mysql-service.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/backend-service.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/frontend-service.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/mysql-pvc.yml --ignore-not-found=true
        
    - name: Adding secrets to kubernetes cluster
      ansible.builtin.shell: |
        kubectl apply -f kubeDeploy/mysql-root-credentials.yml
        kubectl apply -f kubeDeploy/mysql-credentials.yml        
        
    - name: Adding config map to kubernetes cluster
      ansible.builtin.shell: kubectl apply -f kubeDeploy/mysql-configmap.yml    

    - name: Deploying application to kubernetes cluster
      ansible.builtin.shell: |        
        kubectl apply -f kubeDeploy/mysql-pvc.yml
        kubectl apply -f kubeDeploy/mysql-deployment.yml
        kubectl apply -f kubeDeploy/mysql-service.yml
        kubectl apply -f kubeDeploy/backend-deployment.yml
        kubectl apply -f kubeDeploy/backend-service.yml
        kubectl apply -f kubeDeploy/frontend-deployment.yml
        kubectl apply -f kubeDeploy/frontend-service.yml        
